# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-07 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0002_auto_20190808_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('confirmed', 'Confirmed')], default='uploaded', max_length=10),
        ),
    ]
